global:
  scrape_interval: 15s
  scrape_timeout: 10s
  external_labels:
    environment: 'local-dev'
    project: 'ECP'

alerting:
  alertmanagers:
    - static_configs:
        - targets: []  # On branchera Alertmanager au BLOC 7

scrape_configs:

  # Target 1 : Prometheus se scrape lui-même (toujours utile)
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['127.0.0.1:9090']
        labels:
          component: 'monitoring'

  # Target 2 : ECP Network Monitor (remplace ecp_simulator.py)
  - job_name: 'ecp_network_monitor'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['ecp-network-monitor:4000']
        labels:
          component: 'network_monitor'